// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // AddOns
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class AddOn
    {
        public int Id { get; set; } // Id (Primary key)
        public string AddOnId { get; set; } // AddOnId
        public string Version { get; set; } // Version
        public string Name { get; set; } // Name
        public string Description { get; set; } // Description

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AddOnClaim> AddOnClaims { get; set; } // AddOnClaims.FK_dbo.AddOnClaims_dbo.AddOns_AddOnId
        public virtual System.Collections.Generic.ICollection<AddOnCost> AddOnCosts { get; set; } // AddOnCosts.FK_dbo.AddOnCosts_dbo.AddOns_AddOnId
        public virtual System.Collections.Generic.ICollection<Edition> Editions { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<SubscriptionAddOn> SubscriptionAddOns { get; set; } // SubscriptionAddOns.FK_dbo.SubscriptionAddOns_dbo.AddOns_AddOnId

        public AddOn()
        {
            AddOnClaims = new System.Collections.Generic.List<AddOnClaim>();
            AddOnCosts = new System.Collections.Generic.List<AddOnCost>();
            SubscriptionAddOns = new System.Collections.Generic.List<SubscriptionAddOn>();
            Editions = new System.Collections.Generic.List<Edition>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
