// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ApiConnectors
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class ApiConnector
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public string ConnectorEndPoint { get; set; } // ConnectorEndPoint
        public string ApiEndPoint { get; set; } // ApiEndPoint
        public string ExternalCodeSetupEndPoint { get; set; } // ExternalCodeSetupEndPoint

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<ExternalIntegration> ExternalIntegrations { get; set; } // ExternalIntegrations.FK_dbo.ExternalIntegrations_dbo.ApiConnectors_ApiConnectorId

        public ApiConnector()
        {
            ExternalIntegrations = new System.Collections.Generic.List<ExternalIntegration>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
