// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ApiKeys
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class ApiKeyMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApiKey>
    {
        public ApiKeyMapping()
            : this("dbo")
        {
        }

        public ApiKeyMapping(string schema)
        {
            ToTable("ApiKeys", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Key).HasColumnName(@"Key").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Enabled).HasColumnName(@"Enabled").HasColumnType("bit").IsRequired();
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime2").IsOptional();
            Property(x => x.DateLastModeified).HasColumnName(@"DateLastModeified").HasColumnType("datetime2").IsOptional();
            Property(x => x.CreatedById).HasColumnName(@"CreatedById").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.LastModifiedById).HasColumnName(@"LastModifiedById").HasColumnType("nvarchar").IsOptional().HasMaxLength(128);
            Property(x => x.ContactFirst).HasColumnName(@"ContactFirst").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ContactLast).HasColumnName(@"ContactLast").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ContactEmail).HasColumnName(@"ContactEmail").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.OrganisationId).HasColumnName(@"OrganisationId").HasColumnType("int").IsOptional();
            Property(x => x.Company).HasColumnName(@"Company").HasColumnType("nvarchar(max)").IsOptional();

            // Foreign keys
            HasOptional(a => a.CreatedBy).WithMany(b => b.ApiKeys_CreatedById).HasForeignKey(c => c.CreatedById).WillCascadeOnDelete(false); // FK_dbo.ApiKeys_dbo.Users_CreatedById
            HasOptional(a => a.LastModifiedBy).WithMany(b => b.ApiKeys_LastModifiedById).HasForeignKey(c => c.LastModifiedById).WillCascadeOnDelete(false); // FK_dbo.ApiKeys_dbo.Users_LastModifiedById
            HasOptional(a => a.Organisation).WithMany(b => b.ApiKeys).HasForeignKey(c => c.OrganisationId).WillCascadeOnDelete(false); // FK_dbo.ApiKeys_dbo.Organisations_OrganisationId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
