// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsContentTypeAllowedContentType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsContentTypeAllowedContentType
    {
        public int Id { get; set; } // Id (Primary key)
        public int AllowedId { get; set; } // AllowedId (Primary key)
        public int SortOrder { get; set; } // SortOrder


        public CmsContentTypeAllowedContentType()
        {
            SortOrder = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
