// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsContentType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsContentTypeMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CmsContentType>
    {
        public CmsContentTypeMapping()
            : this("dbo")
        {
        }

        public CmsContentTypeMapping(string schema)
        {
            ToTable("cmsContentType", schema);
            HasKey(x => x.Pk);

            Property(x => x.Pk).HasColumnName(@"pk").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NodeId).HasColumnName(@"nodeId").HasColumnType("int").IsRequired();
            Property(x => x.Alias).HasColumnName(@"alias").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Icon).HasColumnName(@"icon").HasColumnType("nvarchar").IsOptional().HasMaxLength(255);
            Property(x => x.Thumbnail).HasColumnName(@"thumbnail").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.Description).HasColumnName(@"description").HasColumnType("nvarchar").IsOptional().HasMaxLength(1500);
            Property(x => x.IsContainer).HasColumnName(@"isContainer").HasColumnType("bit").IsRequired();
            Property(x => x.AllowAtRoot).HasColumnName(@"allowAtRoot").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.UmbracoNode).WithMany(b => b.CmsContentTypes).HasForeignKey(c => c.NodeId).WillCascadeOnDelete(false); // FK_cmsContentType_umbracoNode_id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
