// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsContentMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CmsContent>
    {
        public CmsContentMapping()
            : this("dbo")
        {
        }

        public CmsContentMapping(string schema)
        {
            ToTable("cmsContent", schema);
            HasKey(x => x.Pk);

            Property(x => x.Pk).HasColumnName(@"pk").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.NodeId).HasColumnName(@"nodeId").HasColumnType("int").IsRequired();
            Property(x => x.ContentType).HasColumnName(@"contentType").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.UmbracoNode).WithMany(b => b.CmsContents).HasForeignKey(c => c.NodeId).WillCascadeOnDelete(false); // FK_cmsContent_umbracoNode_id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
