// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsDocumentType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsDocumentType
    {
        public int ContentTypeNodeId { get; set; } // contentTypeNodeId (Primary key)
        public int TemplateNodeId { get; set; } // templateNodeId (Primary key)
        public bool IsDefault { get; set; } // IsDefault

        // Foreign keys
        public virtual UmbracoNode UmbracoNode { get; set; } // FK_cmsDocumentType_umbracoNode_id

        public CmsDocumentType()
        {
            IsDefault = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
