// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsDataType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsDataType
    {
        public int Pk { get; set; } // pk (Primary key)
        public int NodeId { get; set; } // nodeId
        public string PropertyEditorAlias { get; set; } // propertyEditorAlias (length: 255)
        public string DbType { get; set; } // dbType (length: 50)

        // Foreign keys
        public virtual UmbracoNode UmbracoNode { get; set; } // FK_cmsDataType_umbracoNode_id

        public CmsDataType()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
