// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsDictionary
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsDictionaryMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CmsDictionary>
    {
        public CmsDictionaryMapping()
            : this("dbo")
        {
        }

        public CmsDictionaryMapping(string schema)
        {
            ToTable("cmsDictionary", schema);
            HasKey(x => x.Pk);

            Property(x => x.Pk).HasColumnName(@"pk").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Id).HasColumnName(@"id").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Parent).HasColumnName(@"parent").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Key).HasColumnName(@"key").HasColumnType("nvarchar").IsRequired().HasMaxLength(1000);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
