// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsDataTypePreValues
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsDataTypePreValue
    {
        public int Id { get; set; } // id (Primary key)
        public int DatatypeNodeId { get; set; } // datatypeNodeId
        public string Value { get; set; } // value (length: 1073741823)
        public int Sortorder { get; set; } // sortorder
        public string Alias { get; set; } // alias (length: 50)


        public CmsDataTypePreValue()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
