// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsLanguageText
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsLanguageText
    {
        public int Pk { get; set; } // pk (Primary key)
        public int LanguageId { get; set; } // languageId
        public System.Guid UniqueId { get; set; } // UniqueId
        public string Value { get; set; } // value (length: 1000)

        // Foreign keys
        public virtual UmbracoLanguage UmbracoLanguage { get; set; } // FK_cmsLanguageText_umbracoLanguage_id

        public CmsLanguageText()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
