// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsMember
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsMemberMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CmsMember>
    {
        public CmsMemberMapping()
            : this("dbo")
        {
        }

        public CmsMemberMapping(string schema)
        {
            ToTable("cmsMember", schema);
            HasKey(x => x.NodeId);

            Property(x => x.NodeId).HasColumnName(@"nodeId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Email).HasColumnName(@"Email").HasColumnType("nvarchar").IsRequired().HasMaxLength(1000);
            Property(x => x.LoginName).HasColumnName(@"LoginName").HasColumnType("nvarchar").IsRequired().HasMaxLength(1000);
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar").IsRequired().HasMaxLength(1000);

            // Foreign keys
            HasRequired(a => a.UmbracoNode).WithOptional(b => b.CmsMember).WillCascadeOnDelete(false); // FK_cmsMember_umbracoNode_id
            HasMany(t => t.UmbracoNodes).WithMany(t => t.CmsMembers).Map(m =>
            {
                m.ToTable("cmsMember2MemberGroup", "dbo");
                m.MapLeftKey("Member");
                m.MapRightKey("MemberGroup");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
