// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsPropertyTypeGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsPropertyTypeGroupMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<CmsPropertyTypeGroup>
    {
        public CmsPropertyTypeGroupMapping()
            : this("dbo")
        {
        }

        public CmsPropertyTypeGroupMapping(string schema)
        {
            ToTable("cmsPropertyTypeGroup", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ContenttypeNodeId).HasColumnName(@"contenttypeNodeId").HasColumnType("int").IsRequired();
            Property(x => x.Text).HasColumnName(@"text").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.Sortorder).HasColumnName(@"sortorder").HasColumnType("int").IsRequired();
            Property(x => x.UniqueId).HasColumnName(@"uniqueID").HasColumnType("uniqueidentifier").IsRequired();

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
