// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsPropertyType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsPropertyType
    {
        public int Id { get; set; } // id (Primary key)
        public int DataTypeId { get; set; } // dataTypeId
        public int ContentTypeId { get; set; } // contentTypeId
        public int? PropertyTypeGroupId { get; set; } // propertyTypeGroupId
        public string Alias { get; set; } // Alias (length: 255)
        public string Name { get; set; } // Name (length: 255)
        public int SortOrder { get; set; } // sortOrder
        public bool Mandatory { get; set; } // mandatory
        public string ValidationRegExp { get; set; } // validationRegExp (length: 255)
        public string Description { get; set; } // Description (length: 2000)
        public System.Guid UniqueId { get; set; } // UniqueID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CmsPropertyData> CmsPropertyDatas { get; set; } // cmsPropertyData.FK_cmsPropertyData_cmsPropertyType_id
        public virtual System.Collections.Generic.ICollection<CmsTagRelationship> CmsTagRelationships { get; set; } // Many to many mapping

        // Foreign keys
        public virtual CmsPropertyTypeGroup CmsPropertyTypeGroup { get; set; } // FK_cmsPropertyType_cmsPropertyTypeGroup_id

        public CmsPropertyType()
        {
            SortOrder = 0;
            Mandatory = true;
            UniqueId = System.Guid.NewGuid();
            CmsPropertyDatas = new System.Collections.Generic.List<CmsPropertyData>();
            CmsTagRelationships = new System.Collections.Generic.List<CmsTagRelationship>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
