// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsPreviewXml
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsPreviewXml
    {
        public int NodeId { get; set; } // nodeId (Primary key)
        public System.Guid VersionId { get; set; } // versionId (Primary key)
        public System.DateTime Timestamp { get; set; } // timestamp
        public string Xml { get; set; } // xml (length: 1073741823)


        public CmsPreviewXml()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
