// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsTagRelationship
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsTagRelationship
    {
        public int NodeId { get; set; } // nodeId (Primary key)
        public int TagId { get; set; } // tagId (Primary key)
        public int PropertyTypeId { get; set; } // propertyTypeId (Primary key)

        // Foreign keys
        public virtual CmsPropertyType CmsPropertyType { get; set; } // FK_cmsTagRelationship_cmsPropertyType
        public virtual CmsTag CmsTag { get; set; } // FK_cmsTagRelationship_cmsTags_id

        public CmsTagRelationship()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
