// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // cmsTemplate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CmsTemplate
    {
        public int Pk { get; set; } // pk (Primary key)
        public int NodeId { get; set; } // nodeId
        public string Alias { get; set; } // alias (length: 100)
        public string Design { get; set; } // design (length: 1073741823)

        // Foreign keys
        public virtual UmbracoNode UmbracoNode { get; set; } // FK_cmsTemplate_umbracoNode

        public CmsTemplate()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
