// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Assets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_Asset
    {
        public int AssetId { get; set; } // AssetId (Primary key)
        public int ChannelId { get; set; } // ChannelID
        public int TypeId { get; set; } // TypeID
        public string ContentUrl { get; set; } // ContentURL
        public string ContentTitle { get; set; } // ContentTitle
        public string Description { get; set; } // Description
        public System.DateTime? CreatedDate { get; set; } // CreatedDate
        public string ImageFileName { get; set; } // ImageFileName (length: 50)
        public bool? IsActive { get; set; } // IsActive
        public System.DateTime? DeletedDate { get; set; } // DeletedDate

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Coaching_AssetTag> Coaching_AssetTags { get; set; } // AssetTags.FK_Coaching.AssetTags_Coaching.Assets_AssetItemID
        public virtual System.Collections.Generic.ICollection<Coaching_ProgramAsset> Coaching_ProgramAssets { get; set; } // ProgramAssets.FK_Coaching.ProgramAssets_Coaching.Assets_AssetID
        public virtual System.Collections.Generic.ICollection<Coaching_UserFavorite> Coaching_UserFavorites { get; set; } // UserFavorites.FK_dbo.UserFavorites_Coaching.Assets_AssetItemID
        public virtual System.Collections.Generic.ICollection<Coaching_UserRating> Coaching_UserRatings { get; set; } // UserRatings.FK_dbo.UserRatings_Coaching.Assets_AssetItemID
        public virtual System.Collections.Generic.ICollection<Coaching_UserShare> Coaching_UserShares { get; set; } // UserShares.FK_dbo.UserShares_Coaching.Assets_AssetId
        public virtual System.Collections.Generic.ICollection<Step> Steps { get; set; } // Steps.FK_dbo.Steps_Coaching.Assets_AssetId

        // Foreign keys
        public virtual Coaching_AssetType Coaching_AssetType { get; set; } // FK_Coaching.Assets_Coaching.AssetTypes_TypeID
        public virtual Coaching_Channel Coaching_Channel { get; set; } // FK_Coaching.Assets_Coaching.Channels_ChannelID

        public Coaching_Asset()
        {
            Coaching_AssetTags = new System.Collections.Generic.List<Coaching_AssetTag>();
            Coaching_ProgramAssets = new System.Collections.Generic.List<Coaching_ProgramAsset>();
            Steps = new System.Collections.Generic.List<Step>();
            Coaching_UserFavorites = new System.Collections.Generic.List<Coaching_UserFavorite>();
            Coaching_UserRatings = new System.Collections.Generic.List<Coaching_UserRating>();
            Coaching_UserShares = new System.Collections.Generic.List<Coaching_UserShare>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
