// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // StaThemes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_StaTheme
    {
        public int StaThemeId { get; set; } // StaThemeId (Primary key)
        public int StaId { get; set; } // StaId (Primary key)
        public int ThemeId { get; set; } // ThemeId (Primary key)
        public bool IsActive { get; set; } // IsActive (Primary key)
        public string PageTitle { get; set; } // PageTitle (length: 200)
        public string StaUrl { get; set; } // StaUrl (length: 255)

        public Coaching_StaTheme()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
