// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // UserRatings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_UserRating
    {
        public int UserRatingId { get; set; } // UserRatingID (Primary key)
        public int UserId { get; set; } // UserID
        public int AssetItemId { get; set; } // AssetItemID
        public bool Rating { get; set; } // Rating
        public System.DateTime? RatedDate { get; set; } // RatedDate

        // Foreign keys
        public virtual Coaching_Asset Coaching_Asset { get; set; } // FK_dbo.UserRatings_Coaching.Assets_AssetItemID

        public Coaching_UserRating()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
