// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ProgramAssets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_ProgramAsset
    {
        public int ProgramAssetId { get; set; } // ProgramAssetId (Primary key)
        public int ProgramId { get; set; } // ProgramID
        public int AssetId { get; set; } // AssetID
        public int? StageOrder { get; set; } // StageOrder

        // Foreign keys
        public virtual Coaching_Asset Coaching_Asset { get; set; } // FK_Coaching.ProgramAssets_Coaching.Assets_AssetID
        public virtual Coaching_Program Coaching_Program { get; set; } // FK_Coaching.ProgramAssets_Coaching.Programs_ProgramID

        public Coaching_ProgramAsset()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
