// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // AssetTags
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_AssetTagMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Coaching_AssetTag>
    {
        public Coaching_AssetTagMapping()
            : this("Coaching")
        {
        }

        public Coaching_AssetTagMapping(string schema)
        {
            ToTable("AssetTags", schema);
            HasKey(x => x.AssetTagId);

            Property(x => x.AssetTagId).HasColumnName(@"AssetTagID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AssetItemId).HasColumnName(@"AssetItemID").HasColumnType("int").IsRequired();
            Property(x => x.TagId).HasColumnName(@"TagID").HasColumnType("int").IsRequired();

            // Foreign keys
            HasRequired(a => a.Coaching_Asset).WithMany(b => b.Coaching_AssetTags).HasForeignKey(c => c.AssetItemId); // FK_Coaching.AssetTags_Coaching.Assets_AssetItemID
            HasRequired(a => a.Coaching_Tag).WithMany(b => b.Coaching_AssetTags).HasForeignKey(c => c.TagId); // FK_Coaching.AssetTags_Coaching.Tags_TagID
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
