// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // UserShares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_UserShare
    {
        public int UserShareId { get; set; } // UserShareId (Primary key)
        public int SharedByUserId { get; set; } // SharedByUserId
        public int SharedToUserId { get; set; } // SharedToUserId
        public int AssetId { get; set; } // AssetId
        public System.DateTime? DateCreated { get; set; } // DateCreated
        public string Message { get; set; } // Message

        // Foreign keys
        public virtual Coaching_Asset Coaching_Asset { get; set; } // FK_dbo.UserShares_Coaching.Assets_AssetId

        public Coaching_UserShare()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
