// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // AssetTypes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_AssetType
    {
        public int AssetTypeId { get; set; } // AssetTypeID (Primary key)
        public string AssetTypeName { get; set; } // AssetTypeName
        public string Accessor { get; set; } // Accessor
        public string ContentType { get; set; } // ContentType

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Coaching_Asset> Coaching_Assets { get; set; } // Assets.FK_Coaching.Assets_Coaching.AssetTypes_TypeID

        public Coaching_AssetType()
        {
            Coaching_Assets = new System.Collections.Generic.List<Coaching_Asset>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
