// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // AssetTypes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_AssetTypeMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Coaching_AssetType>
    {
        public Coaching_AssetTypeMapping()
            : this("Coaching")
        {
        }

        public Coaching_AssetTypeMapping(string schema)
        {
            ToTable("AssetTypes", schema);
            HasKey(x => x.AssetTypeId);

            Property(x => x.AssetTypeId).HasColumnName(@"AssetTypeID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AssetTypeName).HasColumnName(@"AssetTypeName").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.Accessor).HasColumnName(@"Accessor").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.ContentType).HasColumnName(@"ContentType").HasColumnType("nvarchar(max)").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
