// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Programs
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Coaching_Program
    {
        public int ProgramId { get; set; } // ProgramID (Primary key)
        public int ChannelId { get; set; } // ChannelID
        public string ProgramName { get; set; } // ProgramName
        public string ProgramDescription { get; set; } // ProgramDescription
        public string ImageFileName { get; set; } // ImageFileName (length: 50)
        public bool? IsActive { get; set; } // IsActive
        public System.DateTime? DeletedDate { get; set; } // DeletedDate

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Coaching_ProgramAsset> Coaching_ProgramAssets { get; set; } // ProgramAssets.FK_Coaching.ProgramAssets_Coaching.Programs_ProgramID

        // Foreign keys
        public virtual Coaching_Channel Coaching_Channel { get; set; } // FK_Coaching.Programs_Coaching.Channels_ChannelID

        public Coaching_Program()
        {
            Coaching_ProgramAssets = new System.Collections.Generic.List<Coaching_ProgramAsset>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
