// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ColumnPreferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class ColumnPreference
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public bool Visible { get; set; } // Visible
        public int? TablePreferenceId { get; set; } // TablePreference_Id

        // Foreign keys
        public virtual TablePreference TablePreference { get; set; } // FK_dbo.ColumnPreferences_dbo.TablePreferences_TablePreference_Id

        public ColumnPreference()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
