// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ContactShares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class ContactShare
    {
        public int Id { get; set; } // Id (Primary key)
        public string UserId { get; set; } // UserId
        public System.DateTime? DateShared { get; set; } // DateShared
        public int? ContactId { get; set; } // Contact_Id

        // Foreign keys
        public virtual Contact Contact { get; set; } // FK_dbo.ContactShares_dbo.Contacts_Contact_Id

        public ContactShare()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
