// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ContactShares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class ContactShareMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ContactShare>
    {
        public ContactShareMapping()
            : this("dbo")
        {
        }

        public ContactShareMapping(string schema)
        {
            ToTable("ContactShares", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DateShared).HasColumnName(@"DateShared").HasColumnType("datetime2").IsOptional();
            Property(x => x.ContactId).HasColumnName(@"Contact_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Contact).WithMany(b => b.ContactShares).HasForeignKey(c => c.ContactId).WillCascadeOnDelete(false); // FK_dbo.ContactShares_dbo.Contacts_Contact_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
