// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Contacts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Contact
    {
        public int Id { get; set; } // Id (Primary key)
        public string FirstName { get; set; } // FirstName
        public string LastName { get; set; } // LastName
        public string Title { get; set; } // Title
        public string Location { get; set; } // Location
        public string Email { get; set; } // Email
        public string Phone { get; set; } // Phone
        public string Skype { get; set; } // Skype
        public int OrganisationId { get; set; } // OrganisationId
        public string JobTitle { get; set; } // JobTitle
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime DateLastModeified { get; set; } // DateLastModeified
        public string CreatedById { get; set; } // CreatedById (length: 128)
        public string LastModifiedById { get; set; } // LastModifiedById (length: 128)
        public int? AccountId { get; set; } // AccountId
        public int? LogoImageId { get; set; } // LogoImage_Id
        public string ExternalId { get; set; } // ExternalId
        public int? SalesProcessId { get; set; } // SalesProcessId
        public int? StageId { get; set; } // StageId
        public string Notes { get; set; } // Notes
        public string OfficePhone { get; set; } // OfficePhone
        public string MobilePhone { get; set; } // MobilePhone
        public string OtherPhone { get; set; } // OtherPhone

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<ContactShare> ContactShares { get; set; } // ContactShares.FK_dbo.ContactShares_dbo.Contacts_Contact_Id
        public virtual System.Collections.Generic.ICollection<Deal> Deals { get; set; } // Deals.FK_dbo.Deals_dbo.Contacts_LeadContactId
        public virtual System.Collections.Generic.ICollection<ItemStep> ItemSteps { get; set; } // ItemSteps.FK_dbo.ItemSteps_dbo.Contacts_ContactId
        public virtual System.Collections.Generic.ICollection<LogoImage> LogoImages { get; set; } // LogoImages.FK_dbo.LogoImages_dbo.Contacts_ContactId
        public virtual System.Collections.Generic.ICollection<StandardObjectRelationshipDefintion> StandardObjectRelationshipDefintions { get; set; } // StandardObjectRelationshipDefintions.FK_dbo.StandardTableRelationshipDefintions_dbo.Contacts_Contact_Id
        public virtual System.Collections.Generic.ICollection<StandardRelationship> StandardRelationships { get; set; } // StandardRelationships.FK_dbo.StandardRelationships_dbo.Contacts_Contact_Id
        public virtual System.Collections.Generic.ICollection<StepDocument> StepDocuments { get; set; } // StepDocuments.FK_dbo.StepDocuments_dbo.Contacts_Contact_Id
        public virtual System.Collections.Generic.ICollection<TaskContact> TaskContacts { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<ViewRecord> ViewRecords { get; set; } // ViewRecords.FK_dbo.ViewRecords_dbo.Contacts_ContactId

        // Foreign keys
        public virtual Account Account { get; set; } // FK_dbo.Contacts_dbo.Accounts_AccountId
        public virtual LogoImage LogoImage { get; set; } // FK_dbo.Contacts_dbo.LogoImages_LogoImage_Id
        public virtual Organisation Organisation { get; set; } // FK_dbo.Contacts_dbo.Organisations_OrganisationId
        public virtual SalesProcess SalesProcess { get; set; } // FK_dbo.Contacts_dbo.SalesProcesses_SalesProcessId
        public virtual Stage Stage { get; set; } // FK_dbo.Contacts_dbo.Stages_StageId
        public virtual User CreatedBy { get; set; } // FK_dbo.Contacts_dbo.Users_CreatedById
        public virtual User LastModifiedBy { get; set; } // FK_dbo.Contacts_dbo.Users_LastModifiedById

        public Contact()
        {
            ContactShares = new System.Collections.Generic.List<ContactShare>();
            Deals = new System.Collections.Generic.List<Deal>();
            ItemSteps = new System.Collections.Generic.List<ItemStep>();
            LogoImages = new System.Collections.Generic.List<LogoImage>();
            StandardObjectRelationshipDefintions = new System.Collections.Generic.List<StandardObjectRelationshipDefintion>();
            StandardRelationships = new System.Collections.Generic.List<StandardRelationship>();
            StepDocuments = new System.Collections.Generic.List<StepDocument>();
            TaskContacts = new System.Collections.Generic.List<TaskContact>();
            ViewRecords = new System.Collections.Generic.List<ViewRecord>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
