// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CountryLists
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CountryList
    {
        public int Id { get; set; } // Id (Primary key)
        public string IsoCode { get; set; } // IsoCode
        public string Name { get; set; } // Name
        public string Aliases { get; set; } // Aliases

        public CountryList()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
