// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CustomFieldGroups
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CustomFieldGroup
    {
        public int Id { get; set; } // Id (Primary key)
        public int OrganisationId { get; set; } // OrganisationId
        public string Name { get; set; } // Name
        public int GroupType { get; set; } // GroupType
        public bool IsEnabled { get; set; } // IsEnabled
        public int DisplayOrder { get; set; } // DisplayOrder

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CustomField> CustomFields { get; set; } // CustomFields.FK_dbo.CustomFields_dbo.CustomFieldGroups_CustomFieldGroupId

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.CustomFieldGroups_dbo.Organisations_OrganisationId

        public CustomFieldGroup()
        {
            CustomFields = new System.Collections.Generic.List<CustomField>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
