// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CustomFieldTypeGroup
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CustomFieldTypeGroup
    {
        public int Id { get; set; } // Id (Primary key)
        public int OrganisationId { get; set; } // OrganisationId
        public int FieldType { get; set; } // FieldType
        public bool IsEnabled { get; set; } // IsEnabled
        public int DisplayOrder { get; set; } // DisplayOrder

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.CustomFieldTypeGroup_dbo.Organisations_OrganisationId

        public CustomFieldTypeGroup()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
