// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CustomObjects
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CustomObject
    {
        public long Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public System.DateTime? Created { get; set; } // Created
        public System.DateTime? LastModified { get; set; } // LastModified
        public string CreatedById { get; set; } // CreatedBy_Id (length: 128)
        public string LastModifiedById { get; set; } // LastModifiedBy_Id (length: 128)
        public int? OrganisationId { get; set; } // Organisation_Id
        public string Key { get; set; } // Key
        public int? NumericLimit { get; set; } // NumericLimit
        public bool VrReadOnly { get; set; } // VrReadOnly
        public bool AdminOnly { get; set; } // AdminOnly

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CustomField> CustomFields { get; set; } // CustomFields.FK_dbo.CustomFields_dbo.CustomTables_CustomTable_Id
        public virtual System.Collections.Generic.ICollection<CustomObjectFilter> CustomObjectFilters { get; set; } // CustomObjectFilters.FK_dbo.CustomObjectFilters_dbo.CustomObjects_CustomObjectId
        public virtual System.Collections.Generic.ICollection<CustomObjectRow> CustomObjectRows { get; set; } // CustomObjectRows.FK_dbo.CustomTableRows_dbo.CustomTables_CustomTable_Id
        public virtual System.Collections.Generic.ICollection<StandardObjectRelationshipDefintion> StandardObjectRelationshipDefintions { get; set; } // StandardObjectRelationshipDefintions.FK_dbo.TableRelationships_dbo.CustomTables_CustomTable_Id
        public virtual System.Collections.Generic.ICollection<StandardRelationship> StandardRelationships { get; set; } // StandardRelationships.FK_dbo.StandardRelationships_dbo.CustomObjects_CustomObject_Id

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.CustomTables_dbo.Organisations_Organisation_Id
        public virtual User CreatedBy { get; set; } // FK_dbo.CustomTables_dbo.Users_CreatedBy_Id
        public virtual User LastModifiedBy { get; set; } // FK_dbo.CustomTables_dbo.Users_LastModifiedBy_Id

        public CustomObject()
        {
            VrReadOnly = false;
            AdminOnly = false;
            CustomFields = new System.Collections.Generic.List<CustomField>();
            CustomObjectFilters = new System.Collections.Generic.List<CustomObjectFilter>();
            CustomObjectRows = new System.Collections.Generic.List<CustomObjectRow>();
            StandardObjectRelationshipDefintions = new System.Collections.Generic.List<StandardObjectRelationshipDefintion>();
            StandardRelationships = new System.Collections.Generic.List<StandardRelationship>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
