// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CustomObjectRows
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CustomObjectRow
    {
        public long Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public System.DateTime? Created { get; set; } // Created
        public System.DateTime? LastModified { get; set; } // LastModified
        public string CreatedById { get; set; } // CreatedBy_Id (length: 128)
        public string LastModifiedById { get; set; } // LastModifiedBy_Id (length: 128)
        public int? OrganisationId { get; set; } // Organisation_Id
        public long? CustomObjectId { get; set; } // CustomObject_Id
        public string OwnerId { get; set; } // OwnerId (length: 128)
        public int? SalesProcessId { get; set; } // SalesProcessId
        public int? StageId { get; set; } // StageId
        public string ExternalId { get; set; } // ExternalId

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CustomField> CustomFields { get; set; } // CustomFields.FK_dbo.CustomFields_dbo.CustomTableRows_CustomTableRow_Id
        public virtual System.Collections.Generic.ICollection<CustomObjectRowField> CustomObjectRowFields { get; set; } // CustomObjectRowFields.FK_dbo.CustomTableRowFields_dbo.CustomTableRows_CustomTableRow_Id
        public virtual System.Collections.Generic.ICollection<ItemStep> ItemSteps { get; set; } // ItemSteps.FK_dbo.ItemSteps_dbo.CustomTableRows_CustomTableRowId
        public virtual System.Collections.Generic.ICollection<StandardRelationship> StandardRelationships { get; set; } // StandardRelationships.FK_dbo.StandardRelationships_dbo.CustomTableRows_CustomTableRow_Id
        public virtual System.Collections.Generic.ICollection<StepDocument> StepDocuments { get; set; } // StepDocuments.FK_dbo.StepDocuments_dbo.CustomObjectRows_CustomTableRowId
        public virtual System.Collections.Generic.ICollection<Task> Tasks { get; set; } // Tasks.FK_dbo.Tasks_dbo.CustomObjectRows_CustomObjectRow_Id

        // Foreign keys
        public virtual CustomObject CustomObject { get; set; } // FK_dbo.CustomTableRows_dbo.CustomTables_CustomTable_Id
        public virtual Organisation Organisation { get; set; } // FK_dbo.CustomTableRows_dbo.Organisations_Organisation_Id
        public virtual SalesProcess SalesProcess { get; set; } // FK_dbo.CustomTableRows_dbo.SalesProcesses_SalesProcessId
        public virtual Stage Stage { get; set; } // FK_dbo.CustomTableRows_dbo.Stages_StageId
        public virtual User CreatedBy { get; set; } // FK_dbo.CustomTableRows_dbo.Users_CreatedBy_Id
        public virtual User LastModifiedBy { get; set; } // FK_dbo.CustomTableRows_dbo.Users_LastModifiedBy_Id
        public virtual User Owner { get; set; } // FK_dbo.CustomTableRows_dbo.Users_Owner_Id

        public CustomObjectRow()
        {
            CustomFields = new System.Collections.Generic.List<CustomField>();
            CustomObjectRowFields = new System.Collections.Generic.List<CustomObjectRowField>();
            ItemSteps = new System.Collections.Generic.List<ItemStep>();
            StandardRelationships = new System.Collections.Generic.List<StandardRelationship>();
            StepDocuments = new System.Collections.Generic.List<StepDocument>();
            Tasks = new System.Collections.Generic.List<Task>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
