// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CustomFieldValidations
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CustomFieldValidation
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public string Regex { get; set; } // Regex
        public int FieldType { get; set; } // FieldType
        public string ErrorMessage { get; set; } // ErrorMessage

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CustomField> CustomFields { get; set; } // CustomFields.FK_dbo.CustomFields_dbo.CustomFieldValidations_CustomFieldValidation_Id

        public CustomFieldValidation()
        {
            CustomFields = new System.Collections.Generic.List<CustomField>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
