// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // CustomObjectFilters
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class CustomObjectFilter
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public long CustomObjectId { get; set; } // CustomObjectId
        public string CreatedById { get; set; } // CreatedById (length: 128)
        public string LastModifiedById { get; set; } // LastModifiedById (length: 128)
        public System.DateTime Created { get; set; } // Created
        public System.DateTime LastModified { get; set; } // LastModified

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<CustomObjectFilterField> CustomObjectFilterFields { get; set; } // CustomObjectFilterFields.FK_dbo.CustomObjectFilterFields_dbo.CustomObjectFilters_CustomObjectFilterId

        // Foreign keys
        public virtual CustomObject CustomObject { get; set; } // FK_dbo.CustomObjectFilters_dbo.CustomObjects_CustomObjectId
        public virtual User CreatedBy { get; set; } // FK_dbo.CustomObjectFilters_dbo.Users_CreatedById
        public virtual User LastModifiedBy { get; set; } // FK_dbo.CustomObjectFilters_dbo.Users_LastModifiedById

        public CustomObjectFilter()
        {
            CustomObjectFilterFields = new System.Collections.Generic.List<CustomObjectFilterField>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
