// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // DealContactRoles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class DealContactRole
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public int? OrganisationId { get; set; } // OrganisationId
        public string Accessor { get; set; } // Accessor

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<DealContact> DealContacts { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.DealContactRoles_dbo.Organisations_OrganisationId

        public DealContactRole()
        {
            OrganisationId = 0;
            DealContacts = new System.Collections.Generic.List<DealContact>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
