// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // DealShares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class DealShareMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DealShare>
    {
        public DealShareMapping()
            : this("dbo")
        {
        }

        public DealShareMapping(string schema)
        {
            ToTable("DealShares", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DateShared).HasColumnName(@"DateShared").HasColumnType("datetime2").IsOptional();
            Property(x => x.DealId).HasColumnName(@"Deal_Id").HasColumnType("int").IsOptional();
            Property(x => x.Writable).HasColumnName(@"Writable").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasOptional(a => a.Deal).WithMany(b => b.DealShares).HasForeignKey(c => c.DealId).WillCascadeOnDelete(false); // FK_dbo.DealShares_dbo.Deals_Deal_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
