// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // DealOrgCharts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class DealOrgChart
    {
        public int Id { get; set; } // Id (Primary key)
        public int DealId { get; set; } // DealId
        public double ChartZoom { get; set; } // ChartZoom
        public int X { get; set; } // X
        public int Y { get; set; } // Y

        public DealOrgChart()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
