// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // DealOrgCharts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class DealOrgChartMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DealOrgChart>
    {
        public DealOrgChartMapping()
            : this("dbo")
        {
        }

        public DealOrgChartMapping(string schema)
        {
            ToTable("DealOrgCharts", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DealId).HasColumnName(@"DealId").HasColumnType("int").IsRequired();
            Property(x => x.ChartZoom).HasColumnName(@"ChartZoom").HasColumnType("float").IsRequired();
            Property(x => x.X).HasColumnName(@"X").HasColumnType("int").IsRequired();
            Property(x => x.Y).HasColumnName(@"Y").HasColumnType("int").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
