// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // DealSteps
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class DealStep
    {
        public int DealId { get; set; } // DealId (Primary key)
        public int StepId { get; set; } // StepId (Primary key)
        public string ActionValue { get; set; } // ActionValue
        public int? ActionIdValue { get; set; } // ActionIdValue
        public System.DateTime? CompletedDateTime { get; set; } // CompletedDateTime
        public bool Hidden { get; set; } // Hidden
        public bool Completed { get; set; } // Completed
        public int? ReminderTaskId { get; set; } // ReminderTaskId

        // Foreign keys
        public virtual Deal Deal { get; set; } // FK_dbo.DealSteps_dbo.Deals_DealId
        public virtual ReminderTask ReminderTask { get; set; } // FK_dbo.DealSteps_dbo.ReminderTasks_ReminderTaskId
        public virtual Step Step { get; set; } // FK_dbo.DealSteps_dbo.Steps_StepId

        public DealStep()
        {
            Completed = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
