// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Editions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class EditionMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Edition>
    {
        public EditionMapping()
            : this("dbo")
        {
        }

        public EditionMapping(string schema)
        {
            ToTable("Editions", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Status).HasColumnName(@"Status").HasColumnType("int").IsRequired();
            Property(x => x.EditionLevel).HasColumnName(@"EditionLevel").HasColumnType("int").IsRequired();
            HasMany(t => t.Features).WithMany(t => t.Editions).Map(m =>
            {
                m.ToTable("FeatureEditions", "dbo");
                m.MapLeftKey("Edition_Id");
                m.MapRightKey("Feature_Id");
            });
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
