// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // EmailTemplateConfiguration
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class EmailTemplateConfiguration
    {
        public string TemplateId { get; set; } // TemplateID (Primary key) (length: 128)
        public string AuthorId { get; set; } // AuthorID
        public string AuthorName { get; set; } // AuthorName
        public string Subject { get; set; } // Subject
        public bool? Active { get; set; } // Active
        public int? EmailConfigurationId { get; set; } // EmailConfigurationID
        public bool? Optional { get; set; } // Optional
        public string HtmlTemplate { get; set; } // HtmlTemplate
        public string TextTemplate { get; set; } // TextTemplate
        public bool OptionalEnabledByDefault { get; set; } // OptionalEnabledByDefault

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<EmailTemplate> EmailTemplates { get; set; } // EmailTemplates.FK_dbo.EmailTemplates_dbo.EmailTemplateConfiguration_DotmailerTemplate_TemplateID
        public virtual System.Collections.Generic.ICollection<OrgEmailNotificiationPreference> OrgEmailNotificiationPreferences { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<UserEmailNotificationPreference> UserEmailNotificationPreferences { get; set; } // Many to many mapping

        public EmailTemplateConfiguration()
        {
            OptionalEnabledByDefault = false;
            EmailTemplates = new System.Collections.Generic.List<EmailTemplate>();
            OrgEmailNotificiationPreferences = new System.Collections.Generic.List<OrgEmailNotificiationPreference>();
            UserEmailNotificationPreferences = new System.Collections.Generic.List<UserEmailNotificationPreference>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
