// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // EmailTemplates
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class EmailTemplate
    {
        public int Id { get; set; } // Id (Primary key)
        public string Subject { get; set; } // Subject
        public string DocumentFieldCountentHtml { get; set; } // DocumentFieldCountentHtml
        public string DocumentFieldCountentPlain { get; set; } // DocumentFieldCountentPlain
        public string LanguageCode { get; set; } // LanguageCode
        public int? OrganisationId { get; set; } // OrganisationId
        public bool Active { get; set; } // Active
        public string EmailTemplateConfigurationTemplateId { get; set; } // EmailTemplateConfiguration_TemplateID (length: 128)
        public string EmailTemplateConfigurationId { get; set; } // EmailTemplateConfigurationId
        public int EmailType { get; set; } // EmailType
        public System.DateTime? CreatedDate { get; set; } // CreatedDate
        public System.DateTime? LastModified { get; set; } // LastModified
        public System.DateTime? DeletedDate { get; set; } // DeletedDate

        // Foreign keys
        public virtual EmailTemplateConfiguration EmailTemplateConfiguration { get; set; } // FK_dbo.EmailTemplates_dbo.EmailTemplateConfiguration_DotmailerTemplate_TemplateID
        public virtual Organisation Organisation { get; set; } // FK_dbo.EmailTemplates_dbo.Organisations_OrganisationId

        public EmailTemplate()
        {
            EmailType = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
