// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // EmailTemplateConfiguration
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class EmailTemplateConfigurationMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EmailTemplateConfiguration>
    {
        public EmailTemplateConfigurationMapping()
            : this("dbo")
        {
        }

        public EmailTemplateConfigurationMapping(string schema)
        {
            ToTable("EmailTemplateConfiguration", schema);
            HasKey(x => x.TemplateId);

            Property(x => x.TemplateId).HasColumnName(@"TemplateID").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AuthorId).HasColumnName(@"AuthorID").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AuthorName).HasColumnName(@"AuthorName").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Subject).HasColumnName(@"Subject").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Active).HasColumnName(@"Active").HasColumnType("bit").IsOptional();
            Property(x => x.EmailConfigurationId).HasColumnName(@"EmailConfigurationID").HasColumnType("int").IsOptional();
            Property(x => x.Optional).HasColumnName(@"Optional").HasColumnType("bit").IsOptional();
            Property(x => x.HtmlTemplate).HasColumnName(@"HtmlTemplate").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.TextTemplate).HasColumnName(@"TextTemplate").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.OptionalEnabledByDefault).HasColumnName(@"OptionalEnabledByDefault").HasColumnType("bit").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
