// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Consents
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class IdenServ_ConsentMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IdenServ_Consent>
    {
        public IdenServ_ConsentMapping()
            : this("IdenServ")
        {
        }

        public IdenServ_ConsentMapping(string schema)
        {
            ToTable("Consents", schema);
            HasKey(x => new { x.Subject, x.ClientId });

            Property(x => x.Subject).HasColumnName(@"Subject").HasColumnType("nvarchar").IsRequired().HasMaxLength(200).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ClientId).HasColumnName(@"ClientId").HasColumnType("nvarchar").IsRequired().HasMaxLength(200).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Scopes).HasColumnName(@"Scopes").HasColumnType("nvarchar").IsRequired().HasMaxLength(2000);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
