// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Tokens
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class IdenServ_TokenMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IdenServ_Token>
    {
        public IdenServ_TokenMapping()
            : this("IdenServ")
        {
        }

        public IdenServ_TokenMapping(string schema)
        {
            ToTable("Tokens", schema);
            HasKey(x => new { x.Key, x.TokenType });

            Property(x => x.Key).HasColumnName(@"Key").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TokenType).HasColumnName(@"TokenType").HasColumnType("smallint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SubjectId).HasColumnName(@"SubjectId").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.ClientId).HasColumnName(@"ClientId").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.JsonCode).HasColumnName(@"JsonCode").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.Expiry).HasColumnName(@"Expiry").HasColumnType("datetimeoffset").IsRequired();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
