// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ClientClaims
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class IdenServ_ClientClaim
    {
        public int Id { get; set; } // Id (Primary key)
        public string Type { get; set; } // Type (length: 250)
        public string Value { get; set; } // Value (length: 250)
        public int? ClientId { get; set; } // Client_Id

        // Foreign keys
        public virtual IdenServ_Client IdenServ_Client { get; set; } // FK_IdenServ.ClientClaims_IdenServ.Clients_Client_Id

        public IdenServ_ClientClaim()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
