// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ClientRedirectUris
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class IdenServ_ClientRedirectUriMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IdenServ_ClientRedirectUri>
    {
        public IdenServ_ClientRedirectUriMapping()
            : this("IdenServ")
        {
        }

        public IdenServ_ClientRedirectUriMapping(string schema)
        {
            ToTable("ClientRedirectUris", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Uri).HasColumnName(@"Uri").HasColumnType("nvarchar").IsRequired().HasMaxLength(2000);
            Property(x => x.ClientId).HasColumnName(@"Client_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.IdenServ_Client).WithMany(b => b.IdenServ_ClientRedirectUris).HasForeignKey(c => c.ClientId).WillCascadeOnDelete(false); // FK_IdenServ.ClientRedirectUris_IdenServ.Clients_Client_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
