// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ClientSecrets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class IdenServ_ClientSecretMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<IdenServ_ClientSecret>
    {
        public IdenServ_ClientSecretMapping()
            : this("IdenServ")
        {
        }

        public IdenServ_ClientSecretMapping(string schema)
        {
            ToTable("ClientSecrets", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Value).HasColumnName(@"Value").HasColumnType("nvarchar").IsRequired().HasMaxLength(250);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(2000);
            Property(x => x.Expiration).HasColumnName(@"Expiration").HasColumnType("datetimeoffset").IsOptional();
            Property(x => x.ClientId).HasColumnName(@"Client_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.IdenServ_Client).WithMany(b => b.IdenServ_ClientSecrets).HasForeignKey(c => c.ClientId).WillCascadeOnDelete(false); // FK_IdenServ.ClientSecrets_IdenServ.Clients_Client_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
