// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Invites
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Invite
    {
        public int Id { get; set; } // Id (Primary key)
        public string EmailAccessor { get; set; } // EmailAccessor
        public string Email { get; set; } // Email
        public bool? Accepted { get; set; } // Accepted
        public string UserId { get; set; } // UserId (length: 128)
        public string FirstName { get; set; } // FirstName
        public string LastName { get; set; } // LastName
        public int OrganisationId { get; set; } // OrganisationId

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.Invites_dbo.Organisations_OrganisationId
        public virtual User User { get; set; } // FK_dbo.Invites_dbo.Users_User_Id

        public Invite()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
