// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // NotificationFields
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class NotificationFieldMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<NotificationField>
    {
        public NotificationFieldMapping()
            : this("dbo")
        {
        }

        public NotificationFieldMapping(string schema)
        {
            ToTable("NotificationFields", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FieldName).HasColumnName(@"FieldName").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.OldValue).HasColumnName(@"OldValue").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.NewValue).HasColumnName(@"NewValue").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.NotificationId).HasColumnName(@"Notification_Id").HasColumnType("bigint").IsOptional();

            // Foreign keys
            HasOptional(a => a.Notification).WithMany(b => b.NotificationFields).HasForeignKey(c => c.NotificationId).WillCascadeOnDelete(false); // FK_dbo.NotificationFields_dbo.Notifications_Notification_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
