// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // OrganisationSalesObjectViews
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class OrganisationSalesObjectView
    {
        public int Id { get; set; } // Id (Primary key)
        public int SalesObjectViewId { get; set; } // SalesObjectViewId
        public int OrgId { get; set; } // OrgId
        public int? OrganisationId { get; set; } // Organisation_Id
        public bool IsDefault { get; set; } // IsDefault

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.OrganisationSalesObjectViews_dbo.Organisations_Organisation_Id
        public virtual SalesObjectView SalesObjectView { get; set; } // FK_dbo.OrganisationSalesObjectViews_dbo.SalesObjectViews_SalesObjectViewId

        public OrganisationSalesObjectView()
        {
            IsDefault = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
