// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // OrgEmailNotificiationPreferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class OrgEmailNotificiationPreferenceMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<OrgEmailNotificiationPreference>
    {
        public OrgEmailNotificiationPreferenceMapping()
            : this("dbo")
        {
        }

        public OrgEmailNotificiationPreferenceMapping(string schema)
        {
            ToTable("OrgEmailNotificiationPreferences", schema);
            HasKey(x => new { x.EmailTemplateConfigurationId, x.OrgId });

            Property(x => x.EmailTemplateConfigurationId).HasColumnName(@"EmailTemplateConfigurationId").HasColumnType("nvarchar").IsRequired().HasMaxLength(128).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OrgId).HasColumnName(@"OrgId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ReceiveEmail).HasColumnName(@"ReceiveEmail").HasColumnType("bit").IsRequired();
            Property(x => x.OrganisationId).HasColumnName(@"Organisation_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.Organisation).WithMany(b => b.OrgEmailNotificiationPreferences).HasForeignKey(c => c.OrganisationId).WillCascadeOnDelete(false); // FK_dbo.OrgEmailNotificiationPreferences_dbo.Organisations_Organisation_Id
            HasRequired(a => a.EmailTemplateConfiguration).WithMany(b => b.OrgEmailNotificiationPreferences).HasForeignKey(c => c.EmailTemplateConfigurationId); // FK_dbo.OrgEmailNotificiationPreferences_dbo.EmailTemplateConfiguration_EmailTemplateConfigurationId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
