// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // OrgEmailNotificiationPreferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class OrgEmailNotificiationPreference
    {
        public string EmailTemplateConfigurationId { get; set; } // EmailTemplateConfigurationId (Primary key) (length: 128)
        public int OrgId { get; set; } // OrgId (Primary key)
        public bool ReceiveEmail { get; set; } // ReceiveEmail
        public int? OrganisationId { get; set; } // Organisation_Id

        // Foreign keys
        public virtual EmailTemplateConfiguration EmailTemplateConfiguration { get; set; } // FK_dbo.OrgEmailNotificiationPreferences_dbo.EmailTemplateConfiguration_EmailTemplateConfigurationId
        public virtual Organisation Organisation { get; set; } // FK_dbo.OrgEmailNotificiationPreferences_dbo.Organisations_Organisation_Id

        public OrgEmailNotificiationPreference()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
