// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // PickLists
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class PickList
    {
        public int Id { get; set; } // Id (Primary key)
        public string Accessor { get; set; } // Accessor
        public string Name { get; set; } // Name
        public bool MultipleSelections { get; set; } // MultipleSelections
        public bool MultipleSelectionsAllowed { get; set; } // MultipleSelectionsAllowed
        public int? OrganisationId { get; set; } // OrganisationId

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<PickListOption> PickListOptions { get; set; } // PickListOptions.FK_dbo.PickListOptions_dbo.PickLists_PickListId

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.PickLists_dbo.Organisations_OrganisationId

        public PickList()
        {
            MultipleSelections = false;
            MultipleSelectionsAllowed = false;
            PickListOptions = new System.Collections.Generic.List<PickListOption>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
