// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // SalesObjectViewArchiveItems
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class SalesObjectViewArchiveItemMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesObjectViewArchiveItem>
    {
        public SalesObjectViewArchiveItemMapping()
            : this("dbo")
        {
        }

        public SalesObjectViewArchiveItemMapping(string schema)
        {
            ToTable("SalesObjectViewArchiveItems", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SalesObjectViewArchiveId).HasColumnName(@"SalesObjectViewArchiveId").HasColumnType("int").IsRequired();
            Property(x => x.SalesObjectViewId).HasColumnName(@"SalesObjectViewId").HasColumnType("int").IsRequired();
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.SalesObjectView).WithMany(b => b.SalesObjectViewArchiveItems).HasForeignKey(c => c.SalesObjectViewId); // FK_dbo.SalesObjectViewArchiveItems_dbo.SalesObjectViews_SalesObjectViewId
            HasRequired(a => a.SalesObjectViewArchive).WithMany(b => b.SalesObjectViewArchiveItems).HasForeignKey(c => c.SalesObjectViewArchiveId); // FK_dbo.SalesObjectViewArchiveItems_dbo.SalesObjectViewArchives_SalesObjectViewArchiveId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
