// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // SalesObjectViews
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class SalesObjectViewMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SalesObjectView>
    {
        public SalesObjectViewMapping()
            : this("dbo")
        {
        }

        public SalesObjectViewMapping(string schema)
        {
            ToTable("SalesObjectViews", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.SalesObject).HasColumnName(@"SalesObject").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.ViewType).HasColumnName(@"ViewType").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.SideNavItemId).HasColumnName(@"SideNavItemId").HasColumnType("int").IsOptional();
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.OrgId).HasColumnName(@"OrgId").HasColumnType("int").IsOptional();
            Property(x => x.StcId).HasColumnName(@"StcId").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SideNavItem).WithMany(b => b.SalesObjectViews).HasForeignKey(c => c.SideNavItemId).WillCascadeOnDelete(false); // FK_dbo.SalesObjectViews_dbo.SideNavItems_SideNavItemId
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
