// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // SalesProcesses
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class SalesProcess
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public string Description { get; set; } // Description
        public int? OrganisationId { get; set; } // OrganisationId
        public int SalesProcessStatus { get; set; } // SalesProcessStatus
        public bool StepLevelProbability { get; set; } // StepLevelProbability
        public int? CustomTableId { get; set; } // CustomTableId
        public int EntityType { get; set; } // EntityType
        public string RecordTypeId { get; set; } // RecordTypeId
        public bool AutomaticMandatoryStepProgression { get; set; } // AutomaticMandatoryStepProgression
        public bool? HideProbability { get; set; } // HideProbability
        public bool? HideVerifiableOutcomes { get; set; } // HideVerifiableOutcomes

        // Reverse navigation
        public virtual BuyingProcess BuyingProcess { get; set; } // BuyingProcesses.FK_dbo.BuyingProcesses_dbo.SalesProcesses_Id
        public virtual System.Collections.Generic.ICollection<Account> Accounts { get; set; } // Accounts.FK_dbo.Accounts_dbo.SalesProcesses_SalesProcessId
        public virtual System.Collections.Generic.ICollection<Contact> Contacts { get; set; } // Contacts.FK_dbo.Contacts_dbo.SalesProcesses_SalesProcessId
        public virtual System.Collections.Generic.ICollection<CustomObjectRow> CustomObjectRows { get; set; } // CustomObjectRows.FK_dbo.CustomTableRows_dbo.SalesProcesses_SalesProcessId
        public virtual System.Collections.Generic.ICollection<Deal> Deals { get; set; } // Deals.FK_dbo.Deals_dbo.SalesProcesses_SalesProcessId
        public virtual System.Collections.Generic.ICollection<Stage> Stages { get; set; } // Stages.FK_dbo.Stages_dbo.SalesProcesses_SalesProcessId
        public virtual System.Collections.Generic.ICollection<Task> Tasks { get; set; } // Tasks.FK_dbo.Tasks_dbo.SalesProcesses_SalesProcessId

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.SalesProcesses_dbo.Organisations_OrganisationId

        public SalesProcess()
        {
            SalesProcessStatus = 0;
            StepLevelProbability = false;
            EntityType = 0;
            AutomaticMandatoryStepProgression = false;
            Accounts = new System.Collections.Generic.List<Account>();
            Contacts = new System.Collections.Generic.List<Contact>();
            CustomObjectRows = new System.Collections.Generic.List<CustomObjectRow>();
            Deals = new System.Collections.Generic.List<Deal>();
            Stages = new System.Collections.Generic.List<Stage>();
            Tasks = new System.Collections.Generic.List<Task>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
