// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Searches
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Search
    {
        public int Id { get; set; } // Id (Primary key)
        public int SerachType { get; set; } // SerachType
        public string SearchValue { get; set; } // SearchValue
        public int RuleId { get; set; } // RuleId

        // Foreign keys
        public virtual Rule Rule { get; set; } // FK_dbo.Searches_dbo.Rules_Rule_Id

        public Search()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
