// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // Sections
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class Section
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public string Description { get; set; } // Description
        public int StageId { get; set; } // StageId
        public int OrderInStage { get; set; } // OrderInStage

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<SectionCustomLink> SectionCustomLinks { get; set; } // SectionCustomLinks.FK_dbo.SectionCustomLinks_dbo.Sections_SectionId

        // Foreign keys
        public virtual Stage Stage { get; set; } // FK_dbo.Sections_dbo.Stages_StageId

        public Section()
        {
            SectionCustomLinks = new System.Collections.Generic.List<SectionCustomLink>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
