// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // StandardObjectRelationshipDefintions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class StandardObjectRelationshipDefintion
    {
        public long Id { get; set; } // Id (Primary key)
        public int Relationship { get; set; } // Relationship
        public long? CustomObjectId { get; set; } // CustomObject_Id
        public string StandardObjectType { get; set; } // StandardObjectType
        public string StandardObjectId { get; set; } // StandardObjectId
        public int OnDelete { get; set; } // OnDelete
        public int? OrganisationId { get; set; } // Organisation_Id
        public int? ContactId { get; set; } // Contact_Id
        public int? DealId { get; set; } // Deal_Id
        public int? TaskId { get; set; } // Task_Id
        public int? AccountId { get; set; } // Account_Id
        public string Name { get; set; } // Name
        public string Key { get; set; } // Key
        public string DependencySideLabel { get; set; } // DependencySideLabel
        public string PrincipleSideLabel { get; set; } // PrincipleSideLabel

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<StandardRelationship> StandardRelationships { get; set; } // StandardRelationships.FK_dbo.StandardRelationships_dbo.StandardTableRelationshipDefintions_StandardTableRelationshipDefintion_Id

        // Foreign keys
        public virtual Account Account { get; set; } // FK_dbo.StandardTableRelationshipDefintions_dbo.Accounts_Account_Id
        public virtual Contact Contact { get; set; } // FK_dbo.StandardTableRelationshipDefintions_dbo.Contacts_Contact_Id
        public virtual CustomObject CustomObject { get; set; } // FK_dbo.TableRelationships_dbo.CustomTables_CustomTable_Id
        public virtual Deal Deal { get; set; } // FK_dbo.StandardTableRelationshipDefintions_dbo.Deals_Deal_Id
        public virtual Organisation Organisation { get; set; } // FK_dbo.StandardTableRelationshipDefintions_dbo.Organisations_Organisation_Id
        public virtual Task Task { get; set; } // FK_dbo.StandardTableRelationshipDefintions_dbo.Tasks_Task_Id

        public StandardObjectRelationshipDefintion()
        {
            OnDelete = 0;
            StandardRelationships = new System.Collections.Generic.List<StandardRelationship>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
