// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // StepActionFiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class StepActionFile
    {
        public int Id { get; set; } // Id (Primary key)
        public string FileName { get; set; } // FileName
        public string OriginalFileName { get; set; } // OriginalFileName
        public string ContentType { get; set; } // ContentType

        public StepActionFile()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
