// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // SystemPreferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class SystemPreference
    {
        public int Id { get; set; } // Id (Primary key)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<TablePreference> TablePreferences { get; set; } // TablePreferences.FK_dbo.TablePreferences_dbo.SystemPreferences_SystemPreferences_Id
        public virtual System.Collections.Generic.ICollection<User> Users { get; set; } // Users.FK_dbo.Users_dbo.SystemPreferences_SystemPreferences_Id

        public SystemPreference()
        {
            TablePreferences = new System.Collections.Generic.List<TablePreference>();
            Users = new System.Collections.Generic.List<User>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
