// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // TablePreferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class TablePreferenceMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TablePreference>
    {
        public TablePreferenceMapping()
            : this("dbo")
        {
        }

        public TablePreferenceMapping(string schema)
        {
            ToTable("TablePreferences", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.SystemPreferencesId).HasColumnName(@"SystemPreferences_Id").HasColumnType("int").IsOptional();

            // Foreign keys
            HasOptional(a => a.SystemPreference).WithMany(b => b.TablePreferences).HasForeignKey(c => c.SystemPreferencesId).WillCascadeOnDelete(false); // FK_dbo.TablePreferences_dbo.SystemPreferences_SystemPreferences_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
