// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // TaskTypes
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class TaskType
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public int? OrganisationId { get; set; } // OrganisationId
        public string IconName { get; set; } // IconName

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Task> Tasks { get; set; } // Tasks.FK_dbo.Tasks_dbo.TaskTypes_TaskTypeId

        // Foreign keys
        public virtual Organisation Organisation { get; set; } // FK_dbo.TaskTypes_dbo.Organisations_OrganisationId

        public TaskType()
        {
            Tasks = new System.Collections.Generic.List<Task>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
