// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // TaskContacts
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class TaskContact
    {
        public int TaskId { get; set; } // TaskId (Primary key)
        public int ContactId { get; set; } // ContactId (Primary key)
        public string PictureUrl { get; set; } // PictureURL
        public string Participation { get; set; } // Participation
        public string Support { get; set; } // Support
        public int X { get; set; } // X
        public int Y { get; set; } // Y
        public int Width { get; set; } // Width
        public int Height { get; set; } // Height
        public int Id { get; set; } // Id

        // Foreign keys
        public virtual Contact Contact { get; set; } // FK_dbo.TaskContacts_dbo.Contacts_ContactId
        public virtual Task Task { get; set; } // FK_dbo.TaskContacts_dbo.Tasks_TaskId

        public TaskContact()
        {
            X = 0;
            Y = 0;
            Width = 0;
            Height = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
