// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // TaskShares
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class TaskShareMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TaskShare>
    {
        public TaskShareMapping()
            : this("dbo")
        {
        }

        public TaskShareMapping(string schema)
        {
            ToTable("TaskShares", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserId").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.DateShared).HasColumnName(@"DateShared").HasColumnType("datetime2").IsOptional();
            Property(x => x.TaskId).HasColumnName(@"Task_Id").HasColumnType("int").IsOptional();
            Property(x => x.Writable).HasColumnName(@"Writable").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasOptional(a => a.Task).WithMany(b => b.TaskShares).HasForeignKey(c => c.TaskId).WillCascadeOnDelete(false); // FK_dbo.TaskShares_dbo.Tasks_Task_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
