// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoLog
    {
        public int Id { get; set; } // id (Primary key)
        public int UserId { get; set; } // userId
        public int NodeId { get; set; } // NodeId
        public System.DateTime Datestamp { get; set; } // Datestamp
        public string LogHeader { get; set; } // logHeader (length: 50)
        public string LogComment { get; set; } // logComment (length: 4000)

        public UmbracoLog()
        {
            Datestamp = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
