// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoCacheInstruction
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoCacheInstruction
    {
        public int Id { get; set; } // id (Primary key)
        public System.DateTime UtcStamp { get; set; } // utcStamp
        public string JsonInstruction { get; set; } // jsonInstruction (length: 1073741823)
        public string Originated { get; set; } // originated (length: 500)

        public UmbracoCacheInstruction()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
