// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoRelation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoRelation
    {
        public int Id { get; set; } // id (Primary key)
        public int ParentId { get; set; } // parentId
        public int ChildId { get; set; } // childId
        public int RelType { get; set; } // relType
        public System.DateTime Datetime { get; set; } // datetime
        public string Comment { get; set; } // comment (length: 1000)

        // Foreign keys
        public virtual UmbracoNode Child { get; set; } // FK_umbracoRelation_umbracoNode1
        public virtual UmbracoNode Parent { get; set; } // FK_umbracoRelation_umbracoNode
        public virtual UmbracoRelationType UmbracoRelationType { get; set; } // FK_umbracoRelation_umbracoRelationType_id

        public UmbracoRelation()
        {
            Datetime = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
