// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoRedirectUrl
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoRedirectUrlMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UmbracoRedirectUrl>
    {
        public UmbracoRedirectUrlMapping()
            : this("dbo")
        {
        }

        public UmbracoRedirectUrlMapping(string schema)
        {
            ToTable("umbracoRedirectUrl", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ContentKey).HasColumnName(@"contentKey").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.CreateDateUtc).HasColumnName(@"createDateUtc").HasColumnType("datetime").IsRequired();
            Property(x => x.Url).HasColumnName(@"url").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.UrlHash).HasColumnName(@"urlHash").HasColumnType("nvarchar").IsRequired().HasMaxLength(40);

            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
