// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoUserType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoUserType
    {
        public int Id { get; set; } // id (Primary key)
        public string UserTypeAlias { get; set; } // userTypeAlias (length: 50)
        public string UserTypeName { get; set; } // userTypeName (length: 255)
        public string UserTypeDefaultPermissions { get; set; } // userTypeDefaultPermissions (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<UmbracoUser> UmbracoUsers { get; set; } // umbracoUser.FK_umbracoUser_umbracoUserType_id

        public UmbracoUserType()
        {
            UmbracoUsers = new System.Collections.Generic.List<UmbracoUser>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
