// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoDomains
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoDomain
    {
        public int Id { get; set; } // id (Primary key)
        public int? DomainDefaultLanguage { get; set; } // domainDefaultLanguage
        public int? DomainRootStructureId { get; set; } // domainRootStructureID
        public string DomainName { get; set; } // domainName (length: 255)

        // Foreign keys
        public virtual UmbracoNode UmbracoNode { get; set; } // FK_umbracoDomains_umbracoNode_id

        public UmbracoDomain()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
