// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoAccessRule
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoAccessRule
    {
        public System.Guid Id { get; set; } // id (Primary key)
        public System.Guid AccessId { get; set; } // accessId
        public string RuleValue { get; set; } // ruleValue (length: 255)
        public string RuleType { get; set; } // ruleType (length: 255)
        public System.DateTime CreateDate { get; set; } // createDate
        public System.DateTime UpdateDate { get; set; } // updateDate

        // Foreign keys
        public virtual UmbracoAccess UmbracoAccess { get; set; } // FK_umbracoAccessRule_umbracoAccess_id

        public UmbracoAccessRule()
        {
            CreateDate = System.DateTime.Now;
            UpdateDate = System.DateTime.Now;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
