// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // umbracoAccessRule
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UmbracoAccessRuleMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UmbracoAccessRule>
    {
        public UmbracoAccessRuleMapping()
            : this("dbo")
        {
        }

        public UmbracoAccessRuleMapping(string schema)
        {
            ToTable("umbracoAccessRule", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"id").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AccessId).HasColumnName(@"accessId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.RuleValue).HasColumnName(@"ruleValue").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.RuleType).HasColumnName(@"ruleType").HasColumnType("nvarchar").IsRequired().HasMaxLength(255);
            Property(x => x.CreateDate).HasColumnName(@"createDate").HasColumnType("datetime").IsRequired();
            Property(x => x.UpdateDate).HasColumnName(@"updateDate").HasColumnType("datetime").IsRequired();

            // Foreign keys
            HasRequired(a => a.UmbracoAccess).WithMany(b => b.UmbracoAccessRules).HasForeignKey(c => c.AccessId).WillCascadeOnDelete(false); // FK_umbracoAccessRule_umbracoAccess_id
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
