// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // UserProfiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UserProfile
    {
        public int Id { get; set; } // Id (Primary key)
        public string Culture { get; set; } // Culture
        public string Timezone { get; set; } // Timezone
        public string Currency { get; set; } // Currency

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<User> Users { get; set; } // Users.FK_dbo.Users_dbo.UserProfiles_UserProfileId

        public UserProfile()
        {
            Users = new System.Collections.Generic.List<User>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
