// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // UserProfiles
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UserProfileMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<UserProfile>
    {
        public UserProfileMapping()
            : this("dbo")
        {
        }

        public UserProfileMapping(string schema)
        {
            ToTable("UserProfiles", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Culture).HasColumnName(@"Culture").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Timezone).HasColumnName(@"Timezone").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Currency).HasColumnName(@"Currency").HasColumnType("nvarchar(max)").IsOptional();
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
