// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // UserTargets
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UserTarget
    {
        public int UserTargetId { get; set; } // UserTargetId (Primary key)
        public decimal TargetAmount { get; set; } // TargetAmount
        public System.DateTime StartDate { get; set; } // StartDate
        public System.DateTime EndDate { get; set; } // EndDate
        public string UserId { get; set; } // User_Id (length: 128)

        // Foreign keys
        public virtual User User { get; set; } // FK_dbo.UserTargets_dbo.Users_User_Id

        public UserTarget()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
