// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // UserEmailNotificationPreferences
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class UserEmailNotificationPreference
    {
        public string EmailTemplateConfigurationId { get; set; } // EmailTemplateConfigurationId (Primary key) (length: 128)
        public string UserId { get; set; } // UserId (Primary key) (length: 128)
        public bool ReceiveEmail { get; set; } // ReceiveEmail

        // Foreign keys
        public virtual EmailTemplateConfiguration EmailTemplateConfiguration { get; set; } // FK_dbo.UserEmailNotificationPreferences_dbo.EmailTemplateConfiguration_EmailTemplateConfigurationId
        public virtual User User { get; set; } // FK_dbo.UserEmailNotificationPreferences_dbo.Users_UserId

        public UserEmailNotificationPreference()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
