// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.52
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CustomLogic.LegacyDatabase
{

    // ViewRecords
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.27.0.0")]
    public partial class ViewRecord
    {
        public long Id { get; set; } // Id (Primary key)
        public System.DateTime? DateViewed { get; set; } // DateViewed
        public int? AccountId { get; set; } // AccountId
        public int? ContactId { get; set; } // ContactId
        public int? DealId { get; set; } // DealId
        public int? TaskId { get; set; } // TaskId
        public string Discriminator { get; set; } // Discriminator (length: 128)
        public string UserId { get; set; } // UserId (length: 128)

        // Foreign keys
        public virtual Account Account { get; set; } // FK_dbo.ViewRecords_dbo.Accounts_AccountId
        public virtual Contact Contact { get; set; } // FK_dbo.ViewRecords_dbo.Contacts_ContactId
        public virtual Deal Deal { get; set; } // FK_dbo.ViewRecords_dbo.Deals_DealId
        public virtual Task Task { get; set; } // FK_dbo.ViewRecords_dbo.Tasks_TaskId
        public virtual User User { get; set; } // FK_dbo.ViewRecords_dbo.Users_User_Id

        public ViewRecord()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
